# Generated by Django 4.0.4 on 2024-04-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='title',
            new_name='task',
        ),
    ]
