# Generated by Django 4.0.4 on 2024-04-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_title_todoitem_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='task',
            new_name='title',
        ),
    ]
